import { Generator } from "ts-sql-codegen";
import path from "node:path";

const generator = new Generator({
    schemaPath: path.join(__dirname, "../../config/db/schema.yaml"),
    connectionSourcePath: path.join(
        __dirname,
        "../../datasources/DBConnection"
    ),
    outputDirPath: path.join(__dirname, "../../datasources/generated/"),
    common: {
        primaryKey: {
            isAutoGenerated: true,
        },
    },
    export: {
        extractedColumns: true,
        tableInstances: true,
        rowTypes: true
    },
});

generator
    .generate()
    .then(() => {
        process.exit(0);
    })
    .catch((e) => {
        console.error(e);
        process.exit(1);
    });
